// Generated by CoffeeScript 1.6.1
(function() {
  var io, prompt, socket;

  io = require('socket.io-client');

  prompt = require("prompt");

  socket = io.connect("http://localhost:3000");

  socket.on('connect', function() {
    return console.log("connected");
  });

  socket.on('message', function(msg) {
    return console.log("message: ", msg);
  });

  socket.on('disconnect', function() {
    return console.log("disconnect");
  });

  prompt.message = "# ";

  prompt.delimiter = "";

  prompt.start();

  prompt.get("Any key to exit?", function() {
    return {};
  });

}).call(this);
